[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/"
  status = 200
  to = "/.netlify/functions/index/:splat"
[[redirects]]
force = true
from = "/url"
status = 200
to = "/.netlify/functions/index/:splat"
[[redirects]]
force = true
from = "/*"
status = 200
to = "/index.html"

